Updating to v1.0.0 with  node mapnik v3.7.2
kartotherian/kartotherian pull request #73
Opened 2018-08-03 15:22 UTC by mateusbs17

Updating libraries to match node mapnik v3.72 on kartotherian and its dependencies

2018-08-03 15:28 UTC, thesocialdev commented
@mdholloway this PR is blocked until all the libraries are published, but if you are going to test you should use this code.

2018-08-05 17:17 UTC, mdholloway commented
To get the build passing, looks like we'll need to have the Docker build download the backport of mapnik 3.0.20 from apt.wikimedia.org.  I think you'll need to put back and update these two lines: https://github.com/kartotherian/kartotherian/blob/ddc9f61fad67f21584e15b381cefd521b27abb96/Dockerfile#L3-L4 
which were recently removed in https://github.com/kartotherian/kartotherian/commit/e624b704f12cf69312b0dee0094017e4d364e0f0#diff-3254677a7917c6c01f55212f86c57fbf.

2018-08-05 17:18 UTC, mdholloway commented
Please disregard the last comment, I don't seem to have been looking at the most recent version of this PR. ;)

2018-08-05 17:22 UTC, mdholloway requested changes

2018-08-05 17:22 UTC, mdholloway commented on Dockerfile
> +RUN apt-get update && apt-get install -y nodejs nodejs-legacy git wget python apt-transport-https libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-system-dev libboost-
It is not necessary to explicitly install most of these; they'll be pulled in as needed by libmapnik3.0.

2018-08-05 17:42 UTC, mdholloway requested changes

2018-08-05 17:42 UTC, mdholloway commented on package.json
> +    "colors": "^1.3.1",
This looks like a new dependency.  Where is it used?

2018-08-09 15:21 UTC, mdholloway approved these changes

2018-08-09 15:22 UTC, merged